In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

import joblib

In [2]:
from google.colab import files
uploaded = files.upload()

Saving ford_car_dataset.csv to ford_car_dataset.csv

In [4]:
df = pd.read_csv("ford_car_dataset.csv")

In [5]:
df.head()

     model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1    Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2    Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3   Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4   Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17966 entries, 0 to 17965
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         17966 non-null  object
 1   year          17966 non-null  int64
 2   price         17966 non-null  int64
 3   transmission  17966 non-null  object
 4   mileage       17966 non-null  int64
 5   fuelType      17966 non-null  object
 6   tax           17966 non-null  int64
 7   mpg           17966 non-null  float64
 8   engineSize    17966 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 1.2+ MB

In [7]:
X = df.drop("price", axis=1)

In [8]:
y = df["price"]

In [9]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (17966, 8)
Shape of y: (17966,)

In [10]:
X.select_dtypes(include="object").columns

Index(['model', 'transmission', 'fuelType'], dtype='object')

In [11]:
X = pd.get_dummies(X, drop_first=True).astype(int)

In [12]:
X.head()

,year,mileage,tax,mpg,engineSize,model_ C-MAX,model_ EcoSport,model_ Edge,model_ Escort,model_ Fiesta,...,model_ Tourneo Connect,model_ Tourneo Custom,model_ Transit Tourneo,model_Focus,transmission_Manual,transmission_Semi-Auto,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,2017,15944,150,57,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
1,2018,9083,150,57,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,2017,12456,150,57,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,2019,10460,145,40,1,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,1
4,2019,1482,145,48,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1

In [13]:
scaler = StandardScaler()

num_cols = ['year','mileage','tax','mpg','engineSize']

X[num_cols] = scaler.fit_transform(X[num_cols])

X.head()

,year,mileage,tax,mpg,engineSize,model_ C-MAX,model_ EcoSport,model_ Edge,model_ Escort,model_ Fiesta,...,model_ Tourneo Connect,model_ Tourneo Custom,model_ Transit Tourneo,model_Focus,transmission_Manual,transmission_Semi-Auto,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,0.065128,-0.380998,0.591358,-0.042122,-0.447984,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
1,0.552866,-0.733359,0.591358,-0.042122,-0.447984,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0.065128,-0.560132,0.591358,-0.042122,-0.447984,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,1.040605,-0.662640,0.510727,-1.721198,-0.447984,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,1
4,1.040605,-1.123724,0.510727,-0.931045,-0.447984,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.33,
    random_state=42
)

In [15]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (12037, 34)
X_test: (5929, 34)
y_train: (12037,)
y_test: (5929,)

In [16]:
model = LinearRegression()

In [17]:
model.fit(X_train, y_train)

LinearRegression()

In [18]:
print("Intercept:", model.intercept_)

Intercept: 11607.732472620928

In [19]:
coef = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

coef

                         Feature   Coefficient
0                           year  2.037264e+03
1                        mileage -1.319554e+03
2                            tax -2.121847e+01
3                            mpg -9.890269e+02
4                     engineSize  8.796136e+02
5                   model_ C-MAX  9.718149e+02
6                model_ EcoSport  1.288948e+03
7                    model_ Edge  8.453856e+03
8                  model_ Escort  1.389744e+04
9                  model_ Fiesta  9.264820e+02
10                  model_ Focus  3.018045e+03
11                 model_ Fusion  3.490708e+03
12                 model_ Galaxy  5.692100e+03
13            model_ Grand C-MAX  1.238265e+03
14  model_ Grand Tourneo Connect  4.015996e+03
15                     model_ KA -4.414282e+02
16                    model_ Ka+ -2.909773e+03
17                   model_ Kuga  3.228437e+03
18                 model_ Mondeo  2.420536e+03
19                model_ Mustang  1.302312e+04
20                   model_ Puma  7.219506e+03
21                 model_ Ranger  7.048584e-12
22                  model_ S-MAX  5.535860e+03
23               model_ Streetka  4.547474e-13
24        model_ Tourneo Connect  3.426816e+03
25         model_ Tourneo Custom  5.552723e+03
26        model_ Transit Tourneo  8.705959e+02
27                   model_Focus -5.684411e+02
28           transmission_Manual -5.087086e+02
29        transmission_Semi-Auto -2.477652e+02
30             fuelType_Electric  0.000000e+00
31               fuelType_Hybrid  8.646122e+03
32                fuelType_Other  6.576605e+02
33               fuelType_Petrol -1.299749e+03

In [20]:
y_pred = model.predict(X_test)

In [21]:
print("Predicted Values")
print(y_pred[:10])

Predicted Values
[ 6888.75487917  9328.62297666  9420.53085767  4495.6044587
  2429.68493278 16982.00675592 28491.10791141 12482.71267443
 11373.08042083 17275.68925414]

In [22]:
print("Actual Values")
print(y_test.head(10).values)

Actual Values
[ 6995  8999  7998  5491  3790 18200 22998 11000  7600 14985]

In [23]:
comparison = pd.DataFrame({
    "Actual": y_test.values[:10],
    "Predicted": y_pred[:10]
})

comparison

   Actual     Predicted
0    6995   6888.754879
1    8999   9328.622977
2    7998   9420.530858
3    5491   4495.604459
4    3790   2429.684933
5   18200  16982.006756
6   22998  28491.107911
7   11000  12482.712674
8    7600  11373.080421
9   14985  17275.689254

In [24]:
r2 = r2_score(y_test, y_pred)

print("R² Score:", r2)

R² Score: 0.8396626991294073

In [25]:
joblib.dump(model, "LR_ford_car.pkl")

['LR_ford_car.pkl']

In [26]:
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [27]:
joblib.dump(X.columns.tolist(), "columns.pkl")

['columns.pkl']

In [28]:
import os

os.listdir()

['.config',
 'scaler.pkl',
 'ford_car_dataset.csv',
 'columns.pkl',
 'LR_ford_car.pkl',
 'sample_data']