<a href="https://colab.research.google.com/github/sharvarimhaske/Sharvari-mhaskes-linear-regretion/blob/main/option.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving insurance (1).csv to insurance (1).csv

In [6]:
df = pd.read_csv("insurance (1).csv")

In [7]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [8]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [9]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [10]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["sex"] = le.fit_transform(df["sex"])
df["smoker"] = le.fit_transform(df["smoker"])
df["region"] = le.fit_transform(df["region"])

In [12]:
X = df.drop("charges", axis=1)
y = df["charges"]

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [14]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [15]:
y_pred = model.predict(X_test)

In [16]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))

MAE : 4186.508898366433
MSE : 33635210.431178406
RMSE: 5799.587091438356
R2 Score: 0.7833463107364539

In [17]:
result = pd.DataFrame({
    "Actual Charges": y_test,
    "Predicted Charges": y_pred
})

result.head(10)

      Actual Charges  Predicted Charges
764       9095.06825        8924.407244
887       5272.17580        7116.295018
890      29330.98315       36909.013521
1293      9301.89355        9507.874691
259      33750.29180       27013.350008
1312      4536.25900       10790.779562
899       2117.33885         226.298446
752      14210.53595       16942.715999
1286      3732.62510        1056.630794
707      10264.44210       11267.919973

In [18]:
sample = X.iloc[[0]]

print("Actual Charge:", y.iloc[0])
print("Predicted Charge:", model.predict(sample)[0])

Actual Charge: 16884.924
Predicted Charge: 25139.731338777558

In [19]:
print("Model Accuracy (R²):", model.score(X_test, y_test))

Model Accuracy (R²): 0.7833463107364539